---
title: "Data Acquisition"
author: "Navaneet Sridhar"
---

#Loading the Libraries
```{r}
library(RSQLite)
library(dplyr)
library(httr)
library(glue)
library(jsonlite)
library(keyring)
library("rstudioapi")
library(rvest)

```
#Send GET request to the API
```{r}
 resp <- GET("https://api.openweathermap.org/data/2.5/weather?q=London&appid=a8c19e73b21191e9fa018bef278a9af4")   #Reading content from the website
weather_data <- fromJSON(content(resp, "text")) %>%  
  as.data.frame()
weather_data
```

#Scrape one of the competitor websites of canyon and create a small database.
```{r}
# Set the URL of the website to scrape
url <- "https://www.rosebikes.de/"

# Scrape the website
html <- read_html(url)

# Find the elements that contain the model names
model_names <- html %>%
  html_nodes(".products-slider-tile__product-name") %>%
  html_text()

# Find the elements that contain the prices
prices <- html %>%
  html_nodes(".product-tile-price__current-value") %>%
  html_text()

# Extract the number using regular expressions
price <- gsub("[^0-9.,]", "", prices)  # Remove all non-digit, non-decimal, and non-comma characters

# Create a data frame of the model names and prices
database <- data.frame(
  Model = model_names,
  Price = price
)

# Print the data frame
print(database)


```



